import { API_REUEST } from '@/services/api.service';
import { GetServerSideProps } from 'next'
import Head from 'next/head'
import { Header } from "src/components"

export default function Home(props: HomeProps): JSX.Element {
  console.log(props);

  return (
    <div className='relative h-screen'>
      <Head>
        <title>Next-movie</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo-movie.svg" />
      </Head>
      <Header />
      <main>
        {/* <Hero/> */}
        <section>
          {/* <Row/> */}
        </section>
      </main>
    </div>
  )
}

export const getServerSideProps: GetServerSideProps<HomeProps> = async () => {
  const trending = await fetch(API_REUEST.trending).then(res => res.json())
  return {
    props: {
      trending
    }
  }
}

interface HomeProps {
  trending: any
}