import { IMovie } from '@/interfaces/app.interface';
import { API_REUEST } from '@/services/api.service';
import { GetServerSideProps } from 'next'
import Head from 'next/head'
import { Header, Hero } from "src/components"

export default function Home({ trending }: HomeProps): JSX.Element {
  console.log(trending[0].id);

  return (
    <div className='relative h-screen'>
      <Head>
        <title>Next-movie</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo-movie.svg" />
      </Head>
      <Header />
      <main className='relative pl-4 pb-24 lg:pl-16 lg:space-y-24'>
        <Hero trending={trending} />
        <section>
          {/* <Row/> */}
        </section>
      </main>
    </div>
  )
}

export const getServerSideProps: GetServerSideProps<HomeProps> = async () => {
  const trending = await fetch(API_REUEST.trending).then(res => res.json())
  return {
    props: {
      trending: trending.results
    }
  }
}

interface HomeProps {
  trending: IMovie[]
}